//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBot.Supporter.Main {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class cn_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal cn_Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyBot.Supporter.Main.cn-Lang", typeof(cn_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 您需要.NET 4.5以上才能运行！ 的本地化字符串。
        /// </summary>
        internal static string _Net4_5Needed {
            get {
                return ResourceManager.GetString("_Net4_5Needed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新的MyBot Profile 的本地化字符串。
        /// </summary>
        internal static string AddNewProfile_Button {
            get {
                return ResourceManager.GetString("AddNewProfile_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拦截广告 的本地化字符串。
        /// </summary>
        internal static string AdsBlock_CheckBox {
            get {
                return ResourceManager.GetString("AdsBlock_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级CPU资料显示 的本地化字符串。
        /// </summary>
        internal static string AdvancedCPU {
            get {
                return ResourceManager.GetString("AdvancedCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        internal static string AllSelected {
            get {
                return ResourceManager.GetString("AllSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多开管理已在运行！是否关闭旧管理器？ 的本地化字符串。
        /// </summary>
        internal static string AnotherSupporterIsRunning {
            get {
                return ResourceManager.GetString("AnotherSupporterIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开机自启 的本地化字符串。
        /// </summary>
        internal static string Autorun_CheckBox {
            get {
                return ResourceManager.GetString("Autorun_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新更新，是否要后台下载更新？ 的本地化字符串。
        /// </summary>
        internal static string AutoUpdateFound {
            get {
                return ResourceManager.GetString("AutoUpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电池 的本地化字符串。
        /// </summary>
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑暗 的本地化字符串。
        /// </summary>
        internal static string BlackColor {
            get {
                return ResourceManager.GetString("BlackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入要创建的Bot名字！ 的本地化字符串。
        /// </summary>
        internal static string BotNameNeeded {
            get {
                return ResourceManager.GetString("BotNameNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Bowlers {
            get {
                return ResourceManager.GetString("Bowlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建筑工人： 的本地化字符串。
        /// </summary>
        internal static string Builders {
            get {
                return ResourceManager.GetString("Builders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件！已取消启动该软件！ 的本地化字符串。
        /// </summary>
        internal static string CancelStartOtherPrgram {
            get {
                return ResourceManager.GetString("CancelStartOtherPrgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ClanGame {
            get {
                return ResourceManager.GetString("ClanGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭屏幕节省电源 的本地化字符串。
        /// </summary>
        internal static string Close_LID_CheckBox {
            get {
                return ResourceManager.GetString("Close_LID_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭运行中MyBot和模拟器 的本地化字符串。
        /// </summary>
        internal static string CloseRunningBot_Button {
            get {
                return ResourceManager.GetString("CloseRunningBot_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色主题 的本地化字符串。
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 覆盖其他MyBot设置成当前选中MyBot设置 的本地化字符串。
        /// </summary>
        internal static string CopySettings_Button {
            get {
                return ResourceManager.GetString("CopySettings_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU频率:  的本地化字符串。
        /// </summary>
        internal static string CPUFrequency {
            get {
                return ResourceManager.GetString("CPUFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU最高频率:  的本地化字符串。
        /// </summary>
        internal static string CPUMaxFrequency {
            get {
                return ResourceManager.GetString("CPUMaxFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU最高温度:  的本地化字符串。
        /// </summary>
        internal static string CPUMaxTemp {
            get {
                return ResourceManager.GetString("CPUMaxTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU型号:  的本地化字符串。
        /// </summary>
        internal static string CPUName {
            get {
                return ResourceManager.GetString("CPUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU电力消耗:  的本地化字符串。
        /// </summary>
        internal static string CPUPower {
            get {
                return ResourceManager.GetString("CPUPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU温度:  的本地化字符串。
        /// </summary>
        internal static string CPUTemp {
            get {
                return ResourceManager.GetString("CPUTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新脚本 的本地化字符串。
        /// </summary>
        internal static string CreateCSV {
            get {
                return ResourceManager.GetString("CreateCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始/重置Debug 的本地化字符串。
        /// </summary>
        internal static string CreateDebug_Button {
            get {
                return ResourceManager.GetString("CreateDebug_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CSV 编写器 的本地化字符串。
        /// </summary>
        internal static string CSV_Writer_Button {
            get {
                return ResourceManager.GetString("CSV_Writer_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string CSVNameNeeded {
            get {
                return ResourceManager.GetString("CSVNameNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前选中Profile的切换为: 的本地化字符串。
        /// </summary>
        internal static string CurrentSelectedProfile {
            get {
                return ResourceManager.GetString("CurrentSelectedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现已注射MOD，是否要重新注射？（警告·，新版本·MyBot可能不再支持该MOD或者造成MyBot闪退，请谨慎选择！如果无法启动MyBot，请使用注射器恢复MOD！） 的本地化字符串。
        /// </summary>
        internal static string CustomizeMODFound {
            get {
                return ResourceManager.GetString("CustomizeMODFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已注射MOD 的本地化字符串。
        /// </summary>
        internal static string CustomizeMODFoundTitle {
            get {
                return ResourceManager.GetString("CustomizeMODFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DarckElixirChallenge {
            get {
                return ResourceManager.GetString("DarckElixirChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暗黑重油:  的本地化字符串。
        /// </summary>
        internal static string DarkElixir {
            get {
                return ResourceManager.GetString("DarkElixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DarkElixirHeist {
            get {
                return ResourceManager.GetString("DarkElixirHeist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DestroyAirDefenses {
            get {
                return ResourceManager.GetString("DestroyAirDefenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DestroyAirSweepers {
            get {
                return ResourceManager.GetString("DestroyAirSweepers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毁灭模式 的本地化字符串。
        /// </summary>
        internal static string DestroyingPerformanceMode_Button {
            get {
                return ResourceManager.GetString("DestroyingPerformanceMode_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DestructionChallenge {
            get {
                return ResourceManager.GetString("DestructionChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你不被允许运行除了以exe结尾以外的程序！！ 的本地化字符串。
        /// </summary>
        internal static string DisallowOtherThanEXE {
            get {
                return ResourceManager.GetString("DisallowOtherThanEXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并Bot 的本地化字符串。
        /// </summary>
        internal static string DockBot_Botton {
            get {
                return ResourceManager.GetString("DockBot_Botton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DonateSpells {
            get {
                return ResourceManager.GetString("DonateSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DonateTroops {
            get {
                return ResourceManager.GetString("DonateTroops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载AutoIt 的本地化字符串。
        /// </summary>
        internal static string DownloadAutoIT_Button {
            get {
                return ResourceManager.GetString("DownloadAutoIT_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Dragons {
            get {
                return ResourceManager.GetString("Dragons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已赚取暗黑重油:  的本地化字符串。
        /// </summary>
        internal static string EarnedDarkElixir {
            get {
                return ResourceManager.GetString("EarnedDarkElixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每小时黑油收入: 的本地化字符串。
        /// </summary>
        internal static string EarnedDarkElixirPH {
            get {
                return ResourceManager.GetString("EarnedDarkElixirPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已赚取圣水:  的本地化字符串。
        /// </summary>
        internal static string EarnedElixir {
            get {
                return ResourceManager.GetString("EarnedElixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每小时圣水收入: 的本地化字符串。
        /// </summary>
        internal static string EarnedElixirPH {
            get {
                return ResourceManager.GetString("EarnedElixirPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已赚取金币:  的本地化字符串。
        /// </summary>
        internal static string EarnedGold {
            get {
                return ResourceManager.GetString("EarnedGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每小时金币收入: 的本地化字符串。
        /// </summary>
        internal static string EarnedGoldPH {
            get {
                return ResourceManager.GetString("EarnedGoldPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已赚取奖杯:  的本地化字符串。
        /// </summary>
        internal static string EarnedTrophy {
            get {
                return ResourceManager.GetString("EarnedTrophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每小时奖杯收入:  的本地化字符串。
        /// </summary>
        internal static string EarnedTrophyPH {
            get {
                return ResourceManager.GetString("EarnedTrophyPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Earthquake {
            get {
                return ResourceManager.GetString("Earthquake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改已存在脚本 的本地化字符串。
        /// </summary>
        internal static string EditCSV {
            get {
                return ResourceManager.GetString("EditCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置完毕后请关闭MyBot，从这里再点击开始 的本地化字符串。
        /// </summary>
        internal static string EditMyBot {
            get {
                return ResourceManager.GetString("EditMyBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圣水:  的本地化字符串。
        /// </summary>
        internal static string Elixir {
            get {
                return ResourceManager.GetString("Elixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ElixirChallenge {
            get {
                return ResourceManager.GetString("ElixirChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ElixirEmbezzlement {
            get {
                return ResourceManager.GetString("ElixirEmbezzlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载模拟器 的本地化字符串。
        /// </summary>
        internal static string EmulatorDownload_Button {
            get {
                return ResourceManager.GetString("EmulatorDownload_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理器无法找到已安装模拟器，请自行到生成管理器设置或者到Profile设置内调整 的本地化字符串。
        /// </summary>
        internal static string EmulatorNotFound {
            get {
                return ResourceManager.GetString("EmulatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用切换Profile 的本地化字符串。
        /// </summary>
        internal static string EnableSwitch {
            get {
                return ResourceManager.GetString("EnableSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误！ 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AutoIT错误 的本地化字符串。
        /// </summary>
        internal static string ErrorAutoIT {
            get {
                return ResourceManager.GetString("ErrorAutoIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未经授权或非法使用MyBot错误 的本地化字符串。
        /// </summary>
        internal static string ErrorImgloc {
            get {
                return ResourceManager.GetString("ErrorImgloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误报告 的本地化字符串。
        /// </summary>
        internal static string ErrorTab {
            get {
                return ResourceManager.GetString("ErrorTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特殊通知 的本地化字符串。
        /// </summary>
        internal static string F1GroupBox1 {
            get {
                return ResourceManager.GetString("F1GroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定时通知 的本地化字符串。
        /// </summary>
        internal static string F1GroupBox2 {
            get {
                return ResourceManager.GetString("F1GroupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当CPU运行超过70%，设置CPU频率最高 的本地化字符串。
        /// </summary>
        internal static string F1Label01 {
            get {
                return ResourceManager.GetString("F1Label01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当CPU运行恢复正常，设置CPU频率最高 的本地化字符串。
        /// </summary>
        internal static string F1Label02 {
            get {
                return ResourceManager.GetString("F1Label02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序 的本地化字符串。
        /// </summary>
        internal static string F1Label03 {
            get {
                return ResourceManager.GetString("F1Label03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始小时 的本地化字符串。
        /// </summary>
        internal static string F1Label04 {
            get {
                return ResourceManager.GetString("F1Label04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟 的本地化字符串。
        /// </summary>
        internal static string F1Label05 {
            get {
                return ResourceManager.GetString("F1Label05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束小时 的本地化字符串。
        /// </summary>
        internal static string F1Label06 {
            get {
                return ResourceManager.GetString("F1Label06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络 的本地化字符串。
        /// </summary>
        internal static string F1Label07 {
            get {
                return ResourceManager.GetString("F1Label07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要覆盖的Profile: 的本地化字符串。
        /// </summary>
        internal static string F1Label08 {
            get {
                return ResourceManager.GetString("F1Label08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择主 Profile 的本地化字符串。
        /// </summary>
        internal static string F1Label09 {
            get {
                return ResourceManager.GetString("F1Label09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 屏幕关闭 的本地化字符串。
        /// </summary>
        internal static string F1Label10 {
            get {
                return ResourceManager.GetString("F1Label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备休眠 的本地化字符串。
        /// </summary>
        internal static string F1Label11 {
            get {
                return ResourceManager.GetString("F1Label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络已接受 的本地化字符串。
        /// </summary>
        internal static string F1Label12 {
            get {
                return ResourceManager.GetString("F1Label12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络已发送 的本地化字符串。
        /// </summary>
        internal static string F1Label13 {
            get {
                return ResourceManager.GetString("F1Label13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU使用率 的本地化字符串。
        /// </summary>
        internal static string F1Label14 {
            get {
                return ResourceManager.GetString("F1Label14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RAM使用率 的本地化字符串。
        /// </summary>
        internal static string F1Label15 {
            get {
                return ResourceManager.GetString("F1Label15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载速度 的本地化字符串。
        /// </summary>
        internal static string F1Label16 {
            get {
                return ResourceManager.GetString("F1Label16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传速度 的本地化字符串。
        /// </summary>
        internal static string F1Label17 {
            get {
                return ResourceManager.GetString("F1Label17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换 的本地化字符串。
        /// </summary>
        internal static string F1Label18 {
            get {
                return ResourceManager.GetString("F1Label18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大本营等级 的本地化字符串。
        /// </summary>
        internal static string F1Label19 {
            get {
                return ResourceManager.GetString("F1Label19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定时通知频率 的本地化字符串。
        /// </summary>
        internal static string F1Label24 {
            get {
                return ResourceManager.GetString("F1Label24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后关闭 的本地化字符串。
        /// </summary>
        internal static string F1Label27 {
            get {
                return ResourceManager.GetString("F1Label27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他程序自启设置 的本地化字符串。
        /// </summary>
        internal static string F1TabPage1 {
            get {
                return ResourceManager.GetString("F1TabPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻墙设置 的本地化字符串。
        /// </summary>
        internal static string F1TabPage10 {
            get {
                return ResourceManager.GetString("F1TabPage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电报通知 的本地化字符串。
        /// </summary>
        internal static string F1TabPage11 {
            get {
                return ResourceManager.GetString("F1TabPage11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一般设置 的本地化字符串。
        /// </summary>
        internal static string F1Tabpage2 {
            get {
                return ResourceManager.GetString("F1Tabpage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级设置 的本地化字符串。
        /// </summary>
        internal static string F1Tabpage3 {
            get {
                return ResourceManager.GetString("F1Tabpage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot设置 的本地化字符串。
        /// </summary>
        internal static string F1Tabpage4 {
            get {
                return ResourceManager.GetString("F1Tabpage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多开自启设置 的本地化字符串。
        /// </summary>
        internal static string F1TabPage5 {
            get {
                return ResourceManager.GetString("F1TabPage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他设置 的本地化字符串。
        /// </summary>
        internal static string F1Tabpage6 {
            get {
                return ResourceManager.GetString("F1Tabpage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电脑环境设置 的本地化字符串。
        /// </summary>
        internal static string F1Tabpage7 {
            get {
                return ResourceManager.GetString("F1Tabpage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出管理器后的电源设置 的本地化字符串。
        /// </summary>
        internal static string F1TabPage8 {
            get {
                return ResourceManager.GetString("F1TabPage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知设置 的本地化字符串。
        /// </summary>
        internal static string F1TabPage9 {
            get {
                return ResourceManager.GetString("F1TabPage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FirstInstanceLeftEmpty {
            get {
                return ResourceManager.GetString("FirstInstanceLeftEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot管理器 的本地化字符串。
        /// </summary>
        internal static string Form1 {
            get {
                return ResourceManager.GetString("Form1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Freeze {
            get {
                return ResourceManager.GetString("Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Giants {
            get {
                return ResourceManager.GetString("Giants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Goblins {
            get {
                return ResourceManager.GetString("Goblins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金币:  的本地化字符串。
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string GoldChallenge {
            get {
                return ResourceManager.GetString("GoldChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string GoldGrab {
            get {
                return ResourceManager.GetString("GoldGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Golems {
            get {
                return ResourceManager.GetString("Golems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string GroundTroopsChallenges {
            get {
                return ResourceManager.GetString("GroundTroopsChallenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已关闭/脱离管理器控制 的本地化字符串。
        /// </summary>
        internal static string HadClosed {
            get {
                return ResourceManager.GetString("HadClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Hastle {
            get {
                return ResourceManager.GetString("Hastle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Heal {
            get {
                return ResourceManager.GetString("Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Healers {
            get {
                return ResourceManager.GetString("Healers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助：
        ///
        ///*一般设置内自动产生的Profile可能与模拟器里的游戏账号不相符，如有需要可在高级设置调整。
        ///
        ///*想要取消某个Bot的启动，就直接在高级设置内不要启动的Profile增加#符号，符号周围必须加上空格
        ///
        ///* 有任何错误或者闪退的情况，便在此软件的文件夹内找error.log发给PoH98
        ///
        ///快捷键帮助：
        ///
        ///*Enter直接开始一键启动Bot / 隐藏显示Bot
        ///
        ///* Esc直接退出管理器 / 关闭所有Bot回到设置页面
        ///
        ///*CTRL + G 自动生成Profile 的本地化字符串。
        /// </summary>
        internal static string Help_Message1 {
            get {
                return ResourceManager.GetString("Help_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助:
        ///
        ///* 你可以点击“修改选中MyBot的设置”调整选中的MyBot设置
        ///
        ///* 你可以点击“覆盖其他MyBot设置成当前选中的MyBot设置”覆盖其他MyBot如造兵和进攻等设置成为选中的MyBot设置
        ///
        ///* 你可以点击“关闭运行中的MyBot和模拟器”关闭正在运行的全部MyBot
        ///
        ///* 你可以点击“MyBot注射器”直接修改MyBot的ini设置文件
        ///
        ///* 你可以点击“下载模拟器”直接下载MyBot支持的模拟器以及最佳版本
        ///
        ///* 你可以点击“下载AutoIT”下载MyBot所需要使用的AutoIT 的本地化字符串。
        /// </summary>
        internal static string Help_Message2 {
            get {
                return ResourceManager.GetString("Help_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *这里是用来设置定时启动MyBot以外的软件
        ///
        ///* 请使用隔壁的按钮选择要启动的软件位置
        ///
        ///* 定时启动的软件禁止是恶作剧以及病毒程序，管理器拒绝一切vbs和js脚本类程序 的本地化字符串。
        /// </summary>
        internal static string Help_Message3 {
            get {
                return ResourceManager.GetString("Help_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助: 
        ///
        ///* 点击停止挂机后会自动关闭MyBot
        ///
        ///快捷键帮助：
        ///
        ///* 点击H可以直接隐藏MyBot和模拟器
        ///
        ///* 点击S可以直接显示MyBot和模拟器
        ///
        ///*点击Esc可以直接停止挂机 的本地化字符串。
        /// </summary>
        internal static string Help_Message4 {
            get {
                return ResourceManager.GetString("Help_Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助：
        ///
        ///*管理器将会在选中的Profile资源满后进行切换（如果有设置）
        ///
        /// *管理器只能切换在多开设置内已经被取消启动的Profile （Profile前增加#符号后空格的Profile）
        ///
        /// *管理器将会切换回原本Profile，当其中资源（金币或圣水）低于 1，000，000 或黑油低于 10，000&quot; 的本地化字符串。
        /// </summary>
        internal static string Help_Message5 {
            get {
                return ResourceManager.GetString("Help_Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏MyBot 的本地化字符串。
        /// </summary>
        internal static string HideBot_CheckBox {
            get {
                return ResourceManager.GetString("HideBot_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏模拟器 的本地化字符串。
        /// </summary>
        internal static string HideEmulator_CheckBox {
            get {
                return ResourceManager.GetString("HideEmulator_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从任务栏隐藏 的本地化字符串。
        /// </summary>
        internal static string HideFromTaskBar_CheckBox {
            get {
                return ResourceManager.GetString("HideFromTaskBar_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高性能模式 的本地化字符串。
        /// </summary>
        internal static string HighPerformanceMode_Button {
            get {
                return ResourceManager.GetString("HighPerformanceMode_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Hogs {
            get {
                return ResourceManager.GetString("Hogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时 的本地化字符串。
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12小时格式 的本地化字符串。
        /// </summary>
        internal static string HouSetting_CheckBox {
            get {
                return ResourceManager.GetString("HouSetting_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string HuntforThreeStars {
            get {
                return ResourceManager.GetString("HuntforThreeStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot注射器 的本地化字符串。
        /// </summary>
        internal static string Injector_Button {
            get {
                return ResourceManager.GetString("Injector_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择有效的Profile! 的本地化字符串。
        /// </summary>
        internal static string InvalidProfile {
            get {
                return ResourceManager.GetString("InvalidProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token无效！ 的本地化字符串。
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Lava {
            get {
                return ResourceManager.GetString("Lava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Lightning {
            get {
                return ResourceManager.GetString("Lightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string LootChallenge {
            get {
                return ResourceManager.GetString("LootChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string LordofDestruction {
            get {
                return ResourceManager.GetString("LordofDestruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省电降温模式 的本地化字符串。
        /// </summary>
        internal static string LowPerformaceMode_Button {
            get {
                return ResourceManager.GetString("LowPerformaceMode_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot运行情况 的本地化字符串。
        /// </summary>
        internal static string MBResources {
            get {
                return ResourceManager.GetString("MBResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Miners {
            get {
                return ResourceManager.GetString("Miners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Minions {
            get {
                return ResourceManager.GetString("Minions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分 的本地化字符串。
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string MiscellaneousChallenges {
            get {
                return ResourceManager.GetString("MiscellaneousChallenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string MortarMauling {
            get {
                return ResourceManager.GetString("MortarMauling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot.run教学 的本地化字符串。
        /// </summary>
        internal static string MyBotTutorial_Button {
            get {
                return ResourceManager.GetString("MyBotTutorial_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot有更新！是否后台下载？ 的本地化字符串。
        /// </summary>
        internal static string MyBotUpdateFound {
            get {
                return ResourceManager.GetString("MyBotUpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络情况 的本地化字符串。
        /// </summary>
        internal static string NetStatus {
            get {
                return ResourceManager.GetString("NetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要网络才能打开教学！ 的本地化字符串。
        /// </summary>
        internal static string NetworkNeededForTutorial {
            get {
                return ResourceManager.GetString("NetworkNeededForTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string No_MagicZone {
            get {
                return ResourceManager.GetString("No_MagicZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string NoHeroicsAllowed {
            get {
                return ResourceManager.GetString("NoHeroicsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请在格子里选择有效的Profile 的本地化字符串。
        /// </summary>
        internal static string NoneProfileSelected {
            get {
                return ResourceManager.GetString("NoneProfileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择Profile 的本地化字符串。
        /// </summary>
        internal static string NoneSelected {
            get {
                return ResourceManager.GetString("NoneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络断开 的本地化字符串。
        /// </summary>
        internal static string NoNet {
            get {
                return ResourceManager.GetString("NoNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查网络连接 的本地化字符串。
        /// </summary>
        internal static string NoNetwork {
            get {
                return ResourceManager.GetString("NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认设置 的本地化字符串。
        /// </summary>
        internal static string NormalPerformanceMode_Button {
            get {
                return ResourceManager.GetString("NormalPerformanceMode_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁止任何形式的刷屏！ 的本地化字符串。
        /// </summary>
        internal static string NoSpammers {
            get {
                return ResourceManager.GetString("NoSpammers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提醒 的本地化字符串。
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您只能在这里输入数字与&apos;-&apos;号！ 的本地化字符串。
        /// </summary>
        internal static string NumbersOnly {
            get {
                return ResourceManager.GetString("NumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电源 的本地化字符串。
        /// </summary>
        internal static string OnPower {
            get {
                return ResourceManager.GetString("OnPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否确定覆盖设置？ 的本地化字符串。
        /// </summary>
        internal static string OverWriteConfirmation {
            get {
                return ResourceManager.GetString("OverWriteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功覆盖MyBot设置！ 的本地化字符串。
        /// </summary>
        internal static string OverwriteSuccess {
            get {
                return ResourceManager.GetString("OverwriteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电脑情况 的本地化字符串。
        /// </summary>
        internal static string PCStatus {
            get {
                return ResourceManager.GetString("PCStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Pekkas {
            get {
                return ResourceManager.GetString("Pekkas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PileOfVictories {
            get {
                return ResourceManager.GetString("PileOfVictories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入 的本地化字符串。
        /// </summary>
        internal static string PleaseEnter {
            get {
                return ResourceManager.GetString("PleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PleaseInputEmulatorInstanceNumber {
            get {
                return ResourceManager.GetString("PleaseInputEmulatorInstanceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PleaseInputNameOfProfile {
            get {
                return ResourceManager.GetString("PleaseInputNameOfProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Poison {
            get {
                return ResourceManager.GetString("Poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动调整优先度 的本地化字符串。
        /// </summary>
        internal static string Priority_CheckBox {
            get {
                return ResourceManager.GetString("Priority_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多开设置内的  的本地化字符串。
        /// </summary>
        internal static string ProfileNotFound1 {
            get {
                return ResourceManager.GetString("ProfileNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  不存在于Profile内！请创建新Profile！ 的本地化字符串。
        /// </summary>
        internal static string ProfileNotFound2 {
            get {
                return ResourceManager.GetString("ProfileNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ProfileToInject {
            get {
                return ResourceManager.GetString("ProfileToInject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PurgeChallenges {
            get {
                return ResourceManager.GetString("PurgeChallenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 限制流量使用 的本地化字符串。
        /// </summary>
        internal static string QuotaLimit_CheckBox {
            get {
                return ResourceManager.GetString("QuotaLimit_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Rage {
            get {
                return ResourceManager.GetString("Rage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭其他程序腾出内存 的本地化字符串。
        /// </summary>
        internal static string RAMCleaner_CheckBox {
            get {
                return ResourceManager.GetString("RAMCleaner_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动生成Supporter设置 的本地化字符串。
        /// </summary>
        internal static string Regenerate_Button {
            get {
                return ResourceManager.GetString("Regenerate_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置全部Supporter设置 的本地化字符串。
        /// </summary>
        internal static string Reset_Button {
            get {
                return ResourceManager.GetString("Reset_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定真的要重置所有目前设置吗？ 的本地化字符串。
        /// </summary>
        internal static string ResetConfirmation {
            get {
                return ResourceManager.GetString("ResetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启 的本地化字符串。
        /// </summary>
        internal static string Restart_Button {
            get {
                return ResourceManager.GetString("Restart_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot关闭后马上重启 的本地化字符串。
        /// </summary>
        internal static string RestartBot_CheckBox {
            get {
                return ResourceManager.GetString("RestartBot_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在运行的Bot数量： 的本地化字符串。
        /// </summary>
        internal static string RunningBotCount {
            get {
                return ResourceManager.GetString("RunningBotCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能选择一样的Profile! 的本地化字符串。
        /// </summary>
        internal static string SameProfileSelected {
            get {
                return ResourceManager.GetString("SameProfileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已设置需要运行的Bot数量： 的本地化字符串。
        /// </summary>
        internal static string ScheduledBotCount {
            get {
                return ResourceManager.GetString("ScheduledBotCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定时关机 的本地化字符串。
        /// </summary>
        internal static string ScheduledShutdown_CheckBox {
            get {
                return ResourceManager.GetString("ScheduledShutdown_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SelectedProfile {
            get {
                return ResourceManager.GetString("SelectedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择模拟器！ 的本地化字符串。
        /// </summary>
        internal static string SelectEmulatorNeeded {
            get {
                return ResourceManager.GetString("SelectEmulatorNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SelectEmulatorUsedByProfile {
            get {
                return ResourceManager.GetString("SelectEmulatorUsedByProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SelectSwicthAccount {
            get {
                return ResourceManager.GetString("SelectSwicthAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送Debug日志 的本地化字符串。
        /// </summary>
        internal static string SendDebug_Button {
            get {
                return ResourceManager.GetString("SendDebug_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理器已存在设置， 的本地化字符串。
        /// </summary>
        internal static string SettingsExist {
            get {
                return ResourceManager.GetString("SettingsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关机 的本地化字符串。
        /// </summary>
        internal static string Shutdown_Button {
            get {
                return ResourceManager.GetString("Shutdown_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关机/重启 的本地化字符串。
        /// </summary>
        internal static string Shutdown_ToolTripMenu {
            get {
                return ResourceManager.GetString("Shutdown_ToolTripMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量上限抵达后关机 的本地化字符串。
        /// </summary>
        internal static string ShutdownWhenLimitReached_CheckBox {
            get {
                return ResourceManager.GetString("ShutdownWhenLimitReached_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无网络关机 的本地化字符串。
        /// </summary>
        internal static string ShutdownWhenNoNetwork_CheckBox {
            get {
                return ResourceManager.GetString("ShutdownWhenNoNetwork_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Skeletons {
            get {
                return ResourceManager.GetString("Skeletons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SlayingTheTitans {
            get {
                return ResourceManager.GetString("SlayingTheTitans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抱歉 的本地化字符串。
        /// </summary>
        internal static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string StarCollector {
            get {
                return ResourceManager.GetString("StarCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始启动MyBot 的本地化字符串。
        /// </summary>
        internal static string Start_Button {
            get {
                return ResourceManager.GetString("Start_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改选中MyBot的设置 的本地化字符串。
        /// </summary>
        internal static string StartSelectedMyBot_Button {
            get {
                return ResourceManager.GetString("StartSelectedMyBot_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止挂机 的本地化字符串。
        /// </summary>
        internal static string Stop_Button {
            get {
                return ResourceManager.GetString("Stop_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电池状态停止挂机 的本地化字符串。
        /// </summary>
        internal static string StopBotOnBattery_CheckBox {
            get {
                return ResourceManager.GetString("StopBotOnBattery_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止Debug 的本地化字符串。
        /// </summary>
        internal static string StopDebug_Button {
            get {
                return ResourceManager.GetString("StopDebug_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功！ 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot.Supporter教学 的本地化字符串。
        /// </summary>
        internal static string SupporterTutorial_Button {
            get {
                return ResourceManager.GetString("SupporterTutorial_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源满后切换到选择的Profile 的本地化字符串。
        /// </summary>
        internal static string SwitchProfileIfResourcesFull {
            get {
                return ResourceManager.GetString("SwitchProfileIfResourcesFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot正在关闭 的本地化字符串。
        /// </summary>
        internal static string Telegram_BotClose_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_BotClose_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot正在启动 的本地化字符串。
        /// </summary>
        internal static string Telegram_BotStart_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_BotStart_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理器正在关闭 的本地化字符串。
        /// </summary>
        internal static string Telegram_ClosingSupporter_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_ClosingSupporter_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU情况 的本地化字符串。
        /// </summary>
        internal static string Telegram_CPUStatus_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_CPUStatus_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU过热 的本地化字符串。
        /// </summary>
        internal static string Telegram_OverHeat_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_OverHeat_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在运行的MyBot数量 的本地化字符串。
        /// </summary>
        internal static string Telegram_RunningBotCount_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_RunningBotCount_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已赚取资源 的本地化字符串。
        /// </summary>
        internal static string Telegram_RunningBotEarned_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_RunningBotEarned_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前资源，杯数与工人资料 的本地化字符串。
        /// </summary>
        internal static string Telegram_RunningBotStatus_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_RunningBotStatus_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理器已开始挂机 的本地化字符串。
        /// </summary>
        internal static string Telegram_StartBotting_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_StartBotting_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理器已停止挂机 的本地化字符串。
        /// </summary>
        internal static string Telegram_StopBotting_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_StopBotting_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电报通知频率 的本地化字符串。
        /// </summary>
        internal static string TelegramFrequency {
            get {
                return ResourceManager.GetString("TelegramFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用MyBot管理器！
        ///命令帮助：
        ////s 开始和停止挂机 
        ////en 切换语言到英文
        ////cn 切换语言到中文
        ////cpu 显示目前CPU状态资料 
        ////list 显示目前Profile列表
        ////status 可查看当前全部号资源剩余以及杯段和建筑工人情况
        ////earn 可查看当前每个MyBot已赚取多少资源
        ////h 可隐藏MyBot和模拟器
        ////capt 可截取当前屏幕图片
        ////sh 可显示隐藏的MyBot和模拟器
        ////sd 关闭电脑
        ////re 重启电脑
        ////p 暂停/恢复当前运行的所有MyBot 的本地化字符串。
        /// </summary>
        internal static string TelegramHelpMessage {
            get {
                return ResourceManager.GetString("TelegramHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理器正在关闭！ 的本地化字符串。
        /// </summary>
        internal static string TelegramSupporterClose {
            get {
                return ResourceManager.GetString("TelegramSupporterClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理器正在停止挂机 的本地化字符串。
        /// </summary>
        internal static string TelegramSupporterStop {
            get {
                return ResourceManager.GetString("TelegramSupporterStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新token 的本地化字符串。
        /// </summary>
        internal static string TelegramTokenUpdate_Button {
            get {
                return ResourceManager.GetString("TelegramTokenUpdate_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  次 的本地化字符串。
        /// </summary>
        internal static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 奖杯:  的本地化字符串。
        /// </summary>
        internal static string Trophy {
            get {
                return ResourceManager.GetString("Trophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新手教学 的本地化字符串。
        /// </summary>
        internal static string Tutorial_ToolTripMenu {
            get {
                return ResourceManager.GetString("Tutorial_ToolTripMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到  的本地化字符串。
        /// </summary>
        internal static string UnableToLocate {
            get {
                return ResourceManager.GetString("UnableToLocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新！ 的本地化字符串。
        /// </summary>
        internal static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Valkryines {
            get {
                return ResourceManager.GetString("Valkryines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Village {
            get {
                return ResourceManager.GetString("Village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string WallBreakers {
            get {
                return ResourceManager.GetString("WallBreakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通 的本地化字符串。
        /// </summary>
        internal static string WhiteColor {
            get {
                return ResourceManager.GetString("WhiteColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string WinningStreak {
            get {
                return ResourceManager.GetString("WinningStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Witches {
            get {
                return ResourceManager.GetString("Witches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Wizards {
            get {
                return ResourceManager.GetString("Wizards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string WizardTowerWarfare {
            get {
                return ResourceManager.GetString("WizardTowerWarfare", resourceCulture);
            }
        }
    }
}
