//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBot.Supporter.Main {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyBot.Supporter.Main.en_Lang", typeof(en_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 .NET4.5 above needed 的本地化字符串。
        /// </summary>
        internal static string _Net4_5Needed {
            get {
                return ResourceManager.GetString("_Net4_5Needed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create new MyBot Profile 的本地化字符串。
        /// </summary>
        internal static string AddNewProfile_Button {
            get {
                return ResourceManager.GetString("AddNewProfile_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distance From Redlines 的本地化字符串。
        /// </summary>
        internal static string AddTiles_Tips {
            get {
                return ResourceManager.GetString("AddTiles_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AdsBlock 的本地化字符串。
        /// </summary>
        internal static string AdsBlock_CheckBox {
            get {
                return ResourceManager.GetString("AdsBlock_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advance CPU info 的本地化字符串。
        /// </summary>
        internal static string AdvancedCPU {
            get {
                return ResourceManager.GetString("AdvancedCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string AllSelected {
            get {
                return ResourceManager.GetString("AllSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Congratuations! You are using the newest version! 的本地化字符串。
        /// </summary>
        internal static string AlreadyNewest {
            get {
                return ResourceManager.GetString("AlreadyNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is another Supporter already running, are you want to close it? 的本地化字符串。
        /// </summary>
        internal static string AnotherSupporterIsRunning {
            get {
                return ResourceManager.GetString("AnotherSupporterIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attack Plan 的本地化字符串。
        /// </summary>
        internal static string AttackPlan {
            get {
                return ResourceManager.GetString("AttackPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AutoRun 的本地化字符串。
        /// </summary>
        internal static string Autorun_CheckBox {
            get {
                return ResourceManager.GetString("Autorun_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An update is available. Do you want to download it automaticly? 的本地化字符串。
        /// </summary>
        internal static string AutoUpdateFound {
            get {
                return ResourceManager.GetString("AutoUpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery 的本地化字符串。
        /// </summary>
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input the name of the bot! 的本地化字符串。
        /// </summary>
        internal static string BotNameNeeded {
            get {
                return ResourceManager.GetString("BotNameNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Builders:  的本地化字符串。
        /// </summary>
        internal static string Builders {
            get {
                return ResourceManager.GetString("Builders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Close LID 的本地化字符串。
        /// </summary>
        internal static string Close_LID_CheckBox {
            get {
                return ResourceManager.GetString("Close_LID_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Running MyBot and Emulator 的本地化字符串。
        /// </summary>
        internal static string CloseRunningBot_Button {
            get {
                return ResourceManager.GetString("CloseRunningBot_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme Color 的本地化字符串。
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sycn MyBot Profile Settings 的本地化字符串。
        /// </summary>
        internal static string CopySettings_Button {
            get {
                return ResourceManager.GetString("CopySettings_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Frequency:  的本地化字符串。
        /// </summary>
        internal static string CPUFrequency {
            get {
                return ResourceManager.GetString("CPUFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Max Frequency:  的本地化字符串。
        /// </summary>
        internal static string CPUMaxFrequency {
            get {
                return ResourceManager.GetString("CPUMaxFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Max Temp:  的本地化字符串。
        /// </summary>
        internal static string CPUMaxTemp {
            get {
                return ResourceManager.GetString("CPUMaxTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processor Number:  的本地化字符串。
        /// </summary>
        internal static string CPUName {
            get {
                return ResourceManager.GetString("CPUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Power Usage:  的本地化字符串。
        /// </summary>
        internal static string CPUPower {
            get {
                return ResourceManager.GetString("CPUPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Temperature:  的本地化字符串。
        /// </summary>
        internal static string CPUTemp {
            get {
                return ResourceManager.GetString("CPUTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start/Reset Debug 的本地化字符串。
        /// </summary>
        internal static string CreateDebug_Button {
            get {
                return ResourceManager.GetString("CreateDebug_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CSV Not Found!! 的本地化字符串。
        /// </summary>
        internal static string CSV_NotFound {
            get {
                return ResourceManager.GetString("CSV_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CSV Writer 的本地化字符串。
        /// </summary>
        internal static string CSV_Writer_Button {
            get {
                return ResourceManager.GetString("CSV_Writer_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CSV&apos;s name is not completed! 的本地化字符串。
        /// </summary>
        internal static string CSVNameNeeded {
            get {
                return ResourceManager.GetString("CSVNameNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current running bot count:  的本地化字符串。
        /// </summary>
        internal static string CurrentBotCount {
            get {
                return ResourceManager.GetString("CurrentBotCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting current running bot failed! 的本地化字符串。
        /// </summary>
        internal static string CurrentBotCountFailed {
            get {
                return ResourceManager.GetString("CurrentBotCountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current selected profile will switch to... 的本地化字符串。
        /// </summary>
        internal static string CurrentSelectedProfile {
            get {
                return ResourceManager.GetString("CurrentSelectedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected customize MODs by injector, do you want to apply the MODs on the newer version of MyBot? (Warning! The newer version MyBot might not support the MOD and causing it to crush! You can reverse it using injector again if any bad things happen!) 的本地化字符串。
        /// </summary>
        internal static string CustomizeMODFound {
            get {
                return ResourceManager.GetString("CustomizeMODFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize MOD by Injector found! 的本地化字符串。
        /// </summary>
        internal static string CustomizeMODFoundTitle {
            get {
                return ResourceManager.GetString("CustomizeMODFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DarkElixir:  的本地化字符串。
        /// </summary>
        internal static string DarkElixir {
            get {
                return ResourceManager.GetString("DarkElixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destroy Mode 的本地化字符串。
        /// </summary>
        internal static string DestroyingPerformanceMode_Button {
            get {
                return ResourceManager.GetString("DestroyingPerformanceMode_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destruction Challenges 的本地化字符串。
        /// </summary>
        internal static string DestructionChallenge {
            get {
                return ResourceManager.GetString("DestructionChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock Bot 的本地化字符串。
        /// </summary>
        internal static string DockBot_Button {
            get {
                return ResourceManager.GetString("DockBot_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate Speells 的本地化字符串。
        /// </summary>
        internal static string DonateSpells {
            get {
                return ResourceManager.GetString("DonateSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate troops 的本地化字符串。
        /// </summary>
        internal static string DonateTroops {
            get {
                return ResourceManager.GetString("DonateTroops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download AutoIT 的本地化字符串。
        /// </summary>
        internal static string DownloadAutoIT_Button {
            get {
                return ResourceManager.GetString("DownloadAutoIT_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Dragons {
            get {
                return ResourceManager.GetString("Dragons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distance between troops, more smaller the troop will drop between further 的本地化字符串。
        /// </summary>
        internal static string DropPoints_Tips {
            get {
                return ResourceManager.GetString("DropPoints_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Earned DarkElixir:  的本地化字符串。
        /// </summary>
        internal static string EarnedDarkElixir {
            get {
                return ResourceManager.GetString("EarnedDarkElixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Elixir gain per hour: 的本地化字符串。
        /// </summary>
        internal static string EarnedDarkElixirPH {
            get {
                return ResourceManager.GetString("EarnedDarkElixirPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Earned Elixir:  的本地化字符串。
        /// </summary>
        internal static string EarnedElixir {
            get {
                return ResourceManager.GetString("EarnedElixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elixir gain per hour: 的本地化字符串。
        /// </summary>
        internal static string EarnedElixirPH {
            get {
                return ResourceManager.GetString("EarnedElixirPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Earned Gold:  的本地化字符串。
        /// </summary>
        internal static string EarnedGold {
            get {
                return ResourceManager.GetString("EarnedGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gold gain per hour: 的本地化字符串。
        /// </summary>
        internal static string EarnedGoldPH {
            get {
                return ResourceManager.GetString("EarnedGoldPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Earned Trophy:  的本地化字符串。
        /// </summary>
        internal static string EarnedTrophy {
            get {
                return ResourceManager.GetString("EarnedTrophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trophy gain per hour: 的本地化字符串。
        /// </summary>
        internal static string EarnedTrophyPH {
            get {
                return ResourceManager.GetString("EarnedTrophyPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Earthquake {
            get {
                return ResourceManager.GetString("Earthquake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please close MyBot and restart it using Supporter after setup your MyBot 的本地化字符串。
        /// </summary>
        internal static string EditMyBot {
            get {
                return ResourceManager.GetString("EditMyBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elixir:  的本地化字符串。
        /// </summary>
        internal static string Elixir {
            get {
                return ResourceManager.GetString("Elixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ElixirChallenge {
            get {
                return ResourceManager.GetString("ElixirChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ElixirEmbezzlement {
            get {
                return ResourceManager.GetString("ElixirEmbezzlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Emulator 的本地化字符串。
        /// </summary>
        internal static string EmulatorDownload_Button {
            get {
                return ResourceManager.GetString("EmulatorDownload_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supporter unable to locate any emulator! Please set the emulator by clicking Generate Suppoter Profile or set it by yourself! 的本地化字符串。
        /// </summary>
        internal static string EmulatorNotFound {
            get {
                return ResourceManager.GetString("EmulatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Switch 的本地化字符串。
        /// </summary>
        internal static string EnableSwitch {
            get {
                return ResourceManager.GetString("EnableSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error! 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AutoIT Error 的本地化字符串。
        /// </summary>
        internal static string ErrorAutoIT {
            get {
                return ResourceManager.GetString("ErrorAutoIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImgLoc Error 的本地化字符串。
        /// </summary>
        internal static string ErrorImgloc {
            get {
                return ResourceManager.GetString("ErrorImgloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Report 的本地化字符串。
        /// </summary>
        internal static string ErrorTab {
            get {
                return ResourceManager.GetString("ErrorTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specific situations notification 的本地化字符串。
        /// </summary>
        internal static string F1GroupBox1 {
            get {
                return ResourceManager.GetString("F1GroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixed time notification 的本地化字符串。
        /// </summary>
        internal static string F1GroupBox2 {
            get {
                return ResourceManager.GetString("F1GroupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program Path 的本地化字符串。
        /// </summary>
        internal static string F1Label03 {
            get {
                return ResourceManager.GetString("F1Label03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Time 的本地化字符串。
        /// </summary>
        internal static string F1Label04 {
            get {
                return ResourceManager.GetString("F1Label04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minute 的本地化字符串。
        /// </summary>
        internal static string F1Label05 {
            get {
                return ResourceManager.GetString("F1Label05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Time 的本地化字符串。
        /// </summary>
        internal static string F1Label06 {
            get {
                return ResourceManager.GetString("F1Label06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network 的本地化字符串。
        /// </summary>
        internal static string F1Label07 {
            get {
                return ResourceManager.GetString("F1Label07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Profile to sync 的本地化字符串。
        /// </summary>
        internal static string F1Label08 {
            get {
                return ResourceManager.GetString("F1Label08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Profile 的本地化字符串。
        /// </summary>
        internal static string F1Label09 {
            get {
                return ResourceManager.GetString("F1Label09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen Off Time 的本地化字符串。
        /// </summary>
        internal static string F1Label10 {
            get {
                return ResourceManager.GetString("F1Label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sleep Device Time 的本地化字符串。
        /// </summary>
        internal static string F1Label11 {
            get {
                return ResourceManager.GetString("F1Label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Net Received 的本地化字符串。
        /// </summary>
        internal static string F1Label12 {
            get {
                return ResourceManager.GetString("F1Label12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Net Sended 的本地化字符串。
        /// </summary>
        internal static string F1Label13 {
            get {
                return ResourceManager.GetString("F1Label13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Usage 的本地化字符串。
        /// </summary>
        internal static string F1Label14 {
            get {
                return ResourceManager.GetString("F1Label14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RAM Usage 的本地化字符串。
        /// </summary>
        internal static string F1Label15 {
            get {
                return ResourceManager.GetString("F1Label15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Speed 的本地化字符串。
        /// </summary>
        internal static string F1Label16 {
            get {
                return ResourceManager.GetString("F1Label16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Speed 的本地化字符串。
        /// </summary>
        internal static string F1Label17 {
            get {
                return ResourceManager.GetString("F1Label17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch 的本地化字符串。
        /// </summary>
        internal static string F1Label18 {
            get {
                return ResourceManager.GetString("F1Label18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TH Level 的本地化字符串。
        /// </summary>
        internal static string F1Label19 {
            get {
                return ResourceManager.GetString("F1Label19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frequency of Fixed Time notification 的本地化字符串。
        /// </summary>
        internal static string F1Label24 {
            get {
                return ResourceManager.GetString("F1Label24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string F1Label27 {
            get {
                return ResourceManager.GetString("F1Label27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Program AutoRun Settings 的本地化字符串。
        /// </summary>
        internal static string F1TabPage1 {
            get {
                return ResourceManager.GetString("F1TabPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VPN Settings 的本地化字符串。
        /// </summary>
        internal static string F1TabPage10 {
            get {
                return ResourceManager.GetString("F1TabPage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Telegram Notification 的本地化字符串。
        /// </summary>
        internal static string F1TabPage11 {
            get {
                return ResourceManager.GetString("F1TabPage11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal Settings 的本地化字符串。
        /// </summary>
        internal static string F1Tabpage2 {
            get {
                return ResourceManager.GetString("F1Tabpage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advance Settings 的本地化字符串。
        /// </summary>
        internal static string F1Tabpage3 {
            get {
                return ResourceManager.GetString("F1Tabpage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot Settings 的本地化字符串。
        /// </summary>
        internal static string F1Tabpage4 {
            get {
                return ResourceManager.GetString("F1Tabpage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multi-Bot Settings 的本地化字符串。
        /// </summary>
        internal static string F1TabPage5 {
            get {
                return ResourceManager.GetString("F1TabPage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Setings 的本地化字符串。
        /// </summary>
        internal static string F1Tabpage6 {
            get {
                return ResourceManager.GetString("F1Tabpage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PC Environment Settings 的本地化字符串。
        /// </summary>
        internal static string F1TabPage7 {
            get {
                return ResourceManager.GetString("F1TabPage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Settings after closed 的本地化字符串。
        /// </summary>
        internal static string F1TabPage8 {
            get {
                return ResourceManager.GetString("F1TabPage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Telegram Notification 的本地化字符串。
        /// </summary>
        internal static string F1TabPage9 {
            get {
                return ResourceManager.GetString("F1TabPage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FirstInstanceLeftEmpty {
            get {
                return ResourceManager.GetString("FirstInstanceLeftEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot Supporter 的本地化字符串。
        /// </summary>
        internal static string Form1 {
            get {
                return ResourceManager.GetString("Form1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot Injector 的本地化字符串。
        /// </summary>
        internal static string Form2 {
            get {
                return ResourceManager.GetString("Form2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Freeze {
            get {
                return ResourceManager.GetString("Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Giants {
            get {
                return ResourceManager.GetString("Giants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Goblins {
            get {
                return ResourceManager.GetString("Goblins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gold:  的本地化字符串。
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string GoldChallenge {
            get {
                return ResourceManager.GetString("GoldChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string GoldGrab {
            get {
                return ResourceManager.GetString("GoldGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Golems {
            get {
                return ResourceManager.GetString("Golems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string GroundTroopsChallenges {
            get {
                return ResourceManager.GetString("GroundTroopsChallenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Had Closed / Out of Supporter control 的本地化字符串。
        /// </summary>
        internal static string HadClosed {
            get {
                return ResourceManager.GetString("HadClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Hastle {
            get {
                return ResourceManager.GetString("Hastle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Heal {
            get {
                return ResourceManager.GetString("Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Healers {
            get {
                return ResourceManager.GetString("Healers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This program is designed by PoH98 and used for schedule start for MyBot
        ///
        ///Quick Help: 
        ///
        ///* Auto Generated Profile need to be checked in Advance Settings to make sure no wrong Profile and Emulator matched
        ///
        ///* Just simply add # mark in profile with spacebar around it to disable launch of that profile
        ///
        ///* This Supporter might cause your device sleep and screen off settings reset, Pls kindly use the function in [ OtherSettings\\Power Setting After Closed ] 的本地化字符串。
        /// </summary>
        internal static string Help_Message1 {
            get {
                return ResourceManager.GetString("Help_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help:
        ///
        ///* You can set one MyBot Profile by clicking &quot;Edit Selected Profile Settings&quot; 
        ///
        ///* You can overwrite other MyBot Profile settings such as troops making and attack settings by using &quot;Sync MyBot Profile Settings&quot; button
        ///
        ///* You can close all running MyBot by clicking &quot;Close all Emulators and MyBot&quot; 
        ///
        ///* You can now Inject MyBot ini files with using MyBot Injector&quot;
        ///
        ///* You can download all the MyBot Supported Emulators by clicking &quot;Download Emulator&quot; button
        ///
        ///* You can download AutoIT which needed [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Help_Message2 {
            get {
                return ResourceManager.GetString("Help_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * Here you can set the programs other than MyBot to startup at the schedulled time.
        ///
        ///* Do not use this function for malwares and viruses startup!
        ///
        ///* This function will only start exe type programs.
        ///
        ///* You can tick the network box if your program needs a network to start&quot;; 的本地化字符串。
        /// </summary>
        internal static string Help_Message3 {
            get {
                return ResourceManager.GetString("Help_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help: 
        ///
        ///* After clicking Stop Botting will kill all MyBots and Emulators Processes
        ///
        ///* You can press H for hiding all the bots
        ///
        ///* You can press S for showing all the bots
        ///
        ///* You can stop botting by pressing ESC button 的本地化字符串。
        /// </summary>
        internal static string Help_Message4 {
            get {
                return ResourceManager.GetString("Help_Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助：
        ///
        ///*管理器将会在选中的Profile资源满后进行切换（如果有设置）
        ///
        /// *管理器只能切换在多开设置内已经被取消启动的Profile （Profile前增加#符号后空格的Profile）
        ///
        /// *管理器将会切换回原本Profile，当其中资源（金币或圣水）低于 1，000，000 或黑油低于 10，000&quot; 的本地化字符串。
        /// </summary>
        internal static string Help_Message5 {
            get {
                return ResourceManager.GetString("Help_Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide MyBot 的本地化字符串。
        /// </summary>
        internal static string HideBot_CheckBox {
            get {
                return ResourceManager.GetString("HideBot_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Emulators 的本地化字符串。
        /// </summary>
        internal static string HideEmulator_CheckBox {
            get {
                return ResourceManager.GetString("HideEmulator_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide from Taskbar 的本地化字符串。
        /// </summary>
        internal static string HideFromTaskBar_CheckBox {
            get {
                return ResourceManager.GetString("HideFromTaskBar_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High Performance Mode 的本地化字符串。
        /// </summary>
        internal static string HighPerformanceMode_Button {
            get {
                return ResourceManager.GetString("HighPerformanceMode_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Hogs {
            get {
                return ResourceManager.GetString("Hogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 H 的本地化字符串。
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12-Hour Clock 的本地化字符串。
        /// </summary>
        internal static string HouSetting_CheckBox {
            get {
                return ResourceManager.GetString("HouSetting_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string HuntforThreeStars {
            get {
                return ResourceManager.GetString("HuntforThreeStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot Injector 的本地化字符串。
        /// </summary>
        internal static string Injector_Button {
            get {
                return ResourceManager.GetString("Injector_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid profile! 的本地化字符串。
        /// </summary>
        internal static string InvalidProfile {
            get {
                return ResourceManager.GetString("InvalidProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Telegram Bot Token! 的本地化字符串。
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is normal, set CPU maximum 的本地化字符串。
        /// </summary>
        internal static string IsNormal_Set_Maximum {
            get {
                return ResourceManager.GetString("IsNormal_Set_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is over 60 °C, set CPU maximum 的本地化字符串。
        /// </summary>
        internal static string IsOver60C_Set_Maximum {
            get {
                return ResourceManager.GetString("IsOver60C_Set_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is over 70%, set CPU maximum 的本地化字符串。
        /// </summary>
        internal static string IsOver70_Set_Maximum {
            get {
                return ResourceManager.GetString("IsOver70_Set_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Lava {
            get {
                return ResourceManager.GetString("Lava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Lightning {
            get {
                return ResourceManager.GetString("Lightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string LootChallenge {
            get {
                return ResourceManager.GetString("LootChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string LordofDestruction {
            get {
                return ResourceManager.GetString("LordofDestruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Saving Mode 的本地化字符串。
        /// </summary>
        internal static string LowPerformanceMode_Button {
            get {
                return ResourceManager.GetString("LowPerformanceMode_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot Status 的本地化字符串。
        /// </summary>
        internal static string MBResources {
            get {
                return ResourceManager.GetString("MBResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Miners {
            get {
                return ResourceManager.GetString("Miners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Minions {
            get {
                return ResourceManager.GetString("Minions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M 的本地化字符串。
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string MiscellaneousChallenges {
            get {
                return ResourceManager.GetString("MiscellaneousChallenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string MortarMauling {
            get {
                return ResourceManager.GetString("MortarMauling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot.run tutorial 的本地化字符串。
        /// </summary>
        internal static string MyBotTutorial_Button {
            get {
                return ResourceManager.GetString("MyBotTutorial_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot had updated! Do you want to downlod the latest version? 的本地化字符串。
        /// </summary>
        internal static string MyBotUpdateFound {
            get {
                return ResourceManager.GetString("MyBotUpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Net Status 的本地化字符串。
        /// </summary>
        internal static string NetStatus {
            get {
                return ResourceManager.GetString("NetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string No_MagicZone {
            get {
                return ResourceManager.GetString("No_MagicZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string NoHeroicsAllowed {
            get {
                return ResourceManager.GetString("NoHeroicsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Profile 的本地化字符串。
        /// </summary>
        internal static string NoneProfileSelected {
            get {
                return ResourceManager.GetString("NoneProfileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Connection Lost 的本地化字符串。
        /// </summary>
        internal static string NoNet {
            get {
                return ResourceManager.GetString("NoNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Not Available! 的本地化字符串。
        /// </summary>
        internal static string NoNetwork {
            get {
                return ResourceManager.GetString("NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Mode 的本地化字符串。
        /// </summary>
        internal static string NormalPerformanceMode_Button {
            get {
                return ResourceManager.GetString("NormalPerformanceMode_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您只能在这里输入数字与&apos;-&apos;号！ 的本地化字符串。
        /// </summary>
        internal static string NumbersOnly {
            get {
                return ResourceManager.GetString("NumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OCR read text failed! 的本地化字符串。
        /// </summary>
        internal static string OCR_Failed {
            get {
                return ResourceManager.GetString("OCR_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power 的本地化字符串。
        /// </summary>
        internal static string OnPower {
            get {
                return ResourceManager.GetString("OnPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to overwrite current settings? 的本地化字符串。
        /// </summary>
        internal static string OverWriteConfirmation {
            get {
                return ResourceManager.GetString("OverWriteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overwrite Success! 的本地化字符串。
        /// </summary>
        internal static string OverWriteSuccess {
            get {
                return ResourceManager.GetString("OverWriteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PC Status 的本地化字符串。
        /// </summary>
        internal static string PCStatus {
            get {
                return ResourceManager.GetString("PCStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Pekkas {
            get {
                return ResourceManager.GetString("Pekkas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PileOfVictories {
            get {
                return ResourceManager.GetString("PileOfVictories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Enter 的本地化字符串。
        /// </summary>
        internal static string PleaseEnter {
            get {
                return ResourceManager.GetString("PleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PleaseInputEmulatorInstanceNumber {
            get {
                return ResourceManager.GetString("PleaseInputEmulatorInstanceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PleaseInputNameOfProfile {
            get {
                return ResourceManager.GetString("PleaseInputNameOfProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Poison {
            get {
                return ResourceManager.GetString("Poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Set Priority 的本地化字符串。
        /// </summary>
        internal static string Priority_CheckBox {
            get {
                return ResourceManager.GetString("Priority_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the profile you want to inject 的本地化字符串。
        /// </summary>
        internal static string Profile_ForInject {
            get {
                return ResourceManager.GetString("Profile_ForInject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The profile  的本地化字符串。
        /// </summary>
        internal static string ProfileNotFound1 {
            get {
                return ResourceManager.GetString("ProfileNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  in Multi-Bot is not exist! Please generate it! 的本地化字符串。
        /// </summary>
        internal static string ProfileNotFound2 {
            get {
                return ResourceManager.GetString("ProfileNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ProfileToInject {
            get {
                return ResourceManager.GetString("ProfileToInject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PurgeChallenges {
            get {
                return ResourceManager.GetString("PurgeChallenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Limit Internet Quota Usage 的本地化字符串。
        /// </summary>
        internal static string QuotaLimit_CheckBox {
            get {
                return ResourceManager.GetString("QuotaLimit_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Rage {
            get {
                return ResourceManager.GetString("Rage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close other application to free up RAM 的本地化字符串。
        /// </summary>
        internal static string RAMCleaner_CheckBox {
            get {
                return ResourceManager.GetString("RAMCleaner_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Profiles for Supporter 的本地化字符串。
        /// </summary>
        internal static string Regenerate_Button {
            get {
                return ResourceManager.GetString("Regenerate_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Profiles for Supporter 的本地化字符串。
        /// </summary>
        internal static string Reset_Button {
            get {
                return ResourceManager.GetString("Reset_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart PC 的本地化字符串。
        /// </summary>
        internal static string Restart_Button {
            get {
                return ResourceManager.GetString("Restart_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart Bot when Bot closed 的本地化字符串。
        /// </summary>
        internal static string RestartBot_CheckBox {
            get {
                return ResourceManager.GetString("RestartBot_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot copy a original Profile to itself! 的本地化字符串。
        /// </summary>
        internal static string SameProfileSelected {
            get {
                return ResourceManager.GetString("SameProfileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schedule Shutdown 的本地化字符串。
        /// </summary>
        internal static string ScheduledShutdown_CheckBox {
            get {
                return ResourceManager.GetString("ScheduledShutdown_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S 的本地化字符串。
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select an emulator! 的本地化字符串。
        /// </summary>
        internal static string SelectEmulator {
            get {
                return ResourceManager.GetString("SelectEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Select Emulator! 的本地化字符串。
        /// </summary>
        internal static string SelectEmulatorNeeded {
            get {
                return ResourceManager.GetString("SelectEmulatorNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SelectEmulatorUsedByProfile {
            get {
                return ResourceManager.GetString("SelectEmulatorUsedByProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SelectSwicthAccount {
            get {
                return ResourceManager.GetString("SelectSwicthAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Debug Log 的本地化字符串。
        /// </summary>
        internal static string SendDebug_Button {
            get {
                return ResourceManager.GetString("SendDebug_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shutdown PC 的本地化字符串。
        /// </summary>
        internal static string Shutdown_Button {
            get {
                return ResourceManager.GetString("Shutdown_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shutdown/Restart 的本地化字符串。
        /// </summary>
        internal static string Shutdown_ToolTripMenu {
            get {
                return ResourceManager.GetString("Shutdown_ToolTripMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shutdown when Quota Limit reached 的本地化字符串。
        /// </summary>
        internal static string ShutdownWhenLimitReached_CheckBox {
            get {
                return ResourceManager.GetString("ShutdownWhenLimitReached_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shutdown when no internet connections 的本地化字符串。
        /// </summary>
        internal static string ShutdownWhenNoNetwork_CheckBox {
            get {
                return ResourceManager.GetString("ShutdownWhenNoNetwork_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The side that is used after calculated which side is the main attack side. Such as the main side&apos;s right side, the main side&apos;s left side and so on! 的本地化字符串。
        /// </summary>
        internal static string Side_Tips {
            get {
                return ResourceManager.GetString("Side_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Skeletons {
            get {
                return ResourceManager.GetString("Skeletons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SlayingTheTitans {
            get {
                return ResourceManager.GetString("SlayingTheTitans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry 的本地化字符串。
        /// </summary>
        internal static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string StarCollector {
            get {
                return ResourceManager.GetString("StarCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Botting 的本地化字符串。
        /// </summary>
        internal static string Start_Button {
            get {
                return ResourceManager.GetString("Start_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Selected MyBot Profile Settings 的本地化字符串。
        /// </summary>
        internal static string StartSelectedMyBot_Button {
            get {
                return ResourceManager.GetString("StartSelectedMyBot_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Botting 的本地化字符串。
        /// </summary>
        internal static string Stop_Button {
            get {
                return ResourceManager.GetString("Stop_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Botting On Battery Power 的本地化字符串。
        /// </summary>
        internal static string StopBotOnBattery_CheckBox {
            get {
                return ResourceManager.GetString("StopBotOnBattery_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Debug 的本地化字符串。
        /// </summary>
        internal static string StopDebug_Button {
            get {
                return ResourceManager.GetString("StopDebug_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supporter is starting 的本地化字符串。
        /// </summary>
        internal static string SupporterStarting {
            get {
                return ResourceManager.GetString("SupporterStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot Closing 的本地化字符串。
        /// </summary>
        internal static string Telegram_BotClose_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_BotClose_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Closing MyBot 的本地化字符串。
        /// </summary>
        internal static string Telegram_BotNotInTime1 {
            get {
                return ResourceManager.GetString("Telegram_BotNotInTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 because of not in running time! 的本地化字符串。
        /// </summary>
        internal static string Telegram_BotNotInTime2 {
            get {
                return ResourceManager.GetString("Telegram_BotNotInTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyBot Starting 的本地化字符串。
        /// </summary>
        internal static string Telegram_BotStart_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_BotStart_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supporter is Closing 的本地化字符串。
        /// </summary>
        internal static string Telegram_ClosingSupporter_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_ClosingSupporter_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU status 的本地化字符串。
        /// </summary>
        internal static string Telegram_CPUStatus_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_CPUStatus_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU overheat 的本地化字符串。
        /// </summary>
        internal static string Telegram_OverHeat_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_OverHeat_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current running Bot count 的本地化字符串。
        /// </summary>
        internal static string Telegram_RunningBotCount_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_RunningBotCount_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Earnings from MyBot&apos;s result 的本地化字符串。
        /// </summary>
        internal static string Telegram_RunningBotEarned_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_RunningBotEarned_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Profile Status from MyBot&apos;s result 的本地化字符串。
        /// </summary>
        internal static string Telegram_RunningBotStatus_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_RunningBotStatus_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supporter Start Botting 的本地化字符串。
        /// </summary>
        internal static string Telegram_StartBotting_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_StartBotting_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supporter Stop Botting 的本地化字符串。
        /// </summary>
        internal static string Telegram_StopBotting_CheckBox {
            get {
                return ResourceManager.GetString("Telegram_StopBotting_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Telegram Auto Notify Frequency 的本地化字符串。
        /// </summary>
        internal static string TelegramFrequency {
            get {
                return ResourceManager.GetString("TelegramFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome using MyBot.Supporter.Main!
        ///Command Help: 
        ////s is for starting and stopping bots 
        ////en is changing language to Database.English
        ////cn is changing language to chinese
        ////cpu is for sending CPU informations
        ////list is to shows the bot list and their starting &amp; ending time
        ////h is hide all emulators and bots
        ////sh shows all hidden MyBot and emulators
        ////capt is capturing screenshots
        ////sd is shutdown PC
        ////re is restart PC
        ////p to pause/resume all running MyBots 的本地化字符串。
        /// </summary>
        internal static string TelegramHelpMessage {
            get {
                return ResourceManager.GetString("TelegramHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supporter is closing 的本地化字符串。
        /// </summary>
        internal static string TelegramSupporterClose {
            get {
                return ResourceManager.GetString("TelegramSupporterClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supporter was Stopped Botting 的本地化字符串。
        /// </summary>
        internal static string TelegramSupporterStop {
            get {
                return ResourceManager.GetString("TelegramSupporterStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Token 的本地化字符串。
        /// </summary>
        internal static string TelegramTokenUpdate_Button {
            get {
                return ResourceManager.GetString("TelegramTokenUpdate_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temp 的本地化字符串。
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  times 的本地化字符串。
        /// </summary>
        internal static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trophy:  的本地化字符串。
        /// </summary>
        internal static string Trophy {
            get {
                return ResourceManager.GetString("Trophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Newbie Tutorial 的本地化字符串。
        /// </summary>
        internal static string Tutorial_ToolTripMenu {
            get {
                return ResourceManager.GetString("Tutorial_ToolTripMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string UpdateBox {
            get {
                return ResourceManager.GetString("UpdateBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check MyBot&apos;s Update 的本地化字符串。
        /// </summary>
        internal static string UpdateMyBotButton {
            get {
                return ResourceManager.GetString("UpdateMyBotButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Now! 的本地化字符串。
        /// </summary>
        internal static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Supporter&apos;s Update 的本地化字符串。
        /// </summary>
        internal static string UpdateSupporterButton {
            get {
                return ResourceManager.GetString("UpdateSupporterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usage 的本地化字符串。
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Village 的本地化字符串。
        /// </summary>
        internal static string Village {
            get {
                return ResourceManager.GetString("Village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When CPU 的本地化字符串。
        /// </summary>
        internal static string When_CPU {
            get {
                return ResourceManager.GetString("When_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        internal static string WhiteColor {
            get {
                return ResourceManager.GetString("WhiteColor", resourceCulture);
            }
        }
    }
}
